name: typed_firestore
description: Typed firebase.storage for flutter
homepage: https://github.com/kdy1/typed_firestore
version: 0.4.1

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  built_value: ^7.0.8
  cloud_firestore: ^0.13.0+1
  quiver: '^2.0.0'
  typed_fb_data: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

