name: typed_firestore
description: Typed firebase.storage for flutter
author: DongYoon Kang <kdy1@outlook.kr>
homepage: https://github.com/kdy1/typed_firestore
version: 0.0.4

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  built_value: '^6.1.3'
  cloud_firestore: '^0.9.7'
  quiver: '^2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: '^3.0.0'
  built_value_generator: '^6.1.3'
  build_runner: '^0.10.2'

